apiVersion: v1
kind: ReplicationController
metadata:
  name: jts3servermod-v5.5.4
  namespace: default
  labels:
    version: v1
    app: jts3servermod
spec:
  replicas: 1
  selector:
    version: v5.5.4
    app: jts3servermod
  template:
    metadata:
      labels:
        app: jts3servermod
        version: v5.5.4
    spec:
      containers:
        - image: galexrt/jts3servermod:v5.5.4
          name: jts3servermod
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - name: jts3servermod-storage
            mountPath: /opt/jts3servermod/config
            readOnly: false
      volumes:
      - name: jts3servermod-storage
        hostPath:
          path: /container-data/jts3servermod-data
